# Generated by Django 3.1.3 on 2020-11-05 14:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, max_length=255, quality=0, size=[256, 256], upload_to='images/%Y/%m/%d/'),
        ),
    ]
