# Generated by Django 3.1.3 on 2020-11-04 14:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0008_viewpermission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewpermission',
            unique_together={('user_from', 'user_to')},
        ),
    ]
